---
title: Les bafouilles de Natouille aux pays des geeks
timezone: UTC
collections:
  posts:
    title: Billets
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Les bafouilles de Natouille aux pays des geeks

'
baseurl: ''
twitter_username: nrosenberg
github_username: Natouille
markdown: kramdown
theme: minima
