---
title: Le blog de Natouille
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

description: 'Les bafouilles de Natouille

'
baseurl: ''
twitter_username: nrosenberg
github_username: Natouille
markdown: kramdown
theme: minima
